# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oregami.org
subtitle: Open registry of game information
email: team@oregami.org

excerpt_separator: <!--more-->

social_sites:
  twitter: oregami_org
  facebook: Oregami.org
  github: oregami

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sebeichholz
github_username:  sebeichholz

#permalink: pretty
#permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag


include: ['_pages']

collections:
  posts_de:
    output: true
    permalink: /blog/de/:year/:title
  posts_en:
    output: true
    permalink: /blog/en/:year/:title


defaults:
  - scope:
      path: ""
      type: posts_de
    values:
      language: de
  - scope:
      path: ""
      type: posts_en
    values:
      language: en

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
